services:
  - type: web
    name: n8n-app
    env: node
    region: singapore
    plan: free
    buildCommand: pnpm install --frozen-lockfile; pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: NODE_VERSION
        value: 20.12.2
